NEWS_PROMPTS_PATH = "./prompts/news_prompt.md"
NEWS_DETAIL_PROMPTS_PATH = "./prompts/news_detail_prompt.md"


AI_TRIGGER_WORDS_PATH = "./data/ai/trigger_words.txt"
AI_TRIGGER_PHRASES_PATH = "./data/ai/trigger_phrases.txt"
AFRICA_TRIGGER_WORDS_PATH = "./data/africa/trigger_words.txt"
AFRICA_TRIGGER_PHRASES_PATH = "./data/africa/trigger_phrases.txt"

CATEGORY_TABLE_SCHEMA = """
CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NULL
);
"""

STATISTICS_TABLE_SCHEMA = """
CREATE TABLE IF NOT EXISTS statistics (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    url TEXT UNIQUE NOT NULL,
    stats JSONB,
    updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NULL
);
"""

SOURCE_TABLE_SCHEMA = """
CREATE TABLE IF NOT EXISTS sources (
    id SERIAL PRIMARY KEY,
    url TEXT UNIQUE NOT NULL,
    selector JSONB,
    triggerAfrica BOOLEAN NOT NULL,
    triggerAi BOOLEAN NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NULL
);
"""

AUTHORS_TABLE_SCHEMA = """
CREATE TABLE IF NOT EXISTS authors (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    url TEXT UNIQUE,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
"""

NEWS_TABLE_SCHEMA = """
CREATE TABLE IF NOT EXISTS news (
    id SERIAL PRIMARY KEY,
    sourceId BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    categoryId BIGINT DEFAULT NULL REFERENCES sources(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    url TEXT UNIQUE NOT NULL,
    authorId BIGINT REFERENCES authors(id) ON DELETE SET NULL,
    body TEXT NOT NULL,
    postDate TIMESTAMP WITH TIME ZONE,
    imageUrl TEXT,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
"""
