# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import rpc
import warnings

from rpc.services import source_pb2 as grpc_dot_services_dot_source__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = rpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc/services/source_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SourceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addSource = channel.unary_unary(
                '/source.SourceService/addSource',
                request_serializer=grpc_dot_services_dot_source__pb2.SourceRequest.SerializeToString,
                response_deserializer=grpc_dot_services_dot_source__pb2.SourceResponse.FromString,
                _registered_method=True)


class SourceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(rpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SourceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addSource': rpc.unary_unary_rpc_method_handler(
                    servicer.addSource,
                    request_deserializer=grpc_dot_services_dot_source__pb2.SourceRequest.FromString,
                    response_serializer=grpc_dot_services_dot_source__pb2.SourceResponse.SerializeToString,
            ),
    }
    generic_handler = rpc.method_handlers_generic_handler(
            'source.SourceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('source.SourceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SourceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return rpc.experimental.unary_unary(
            request,
            target,
            '/source.SourceService/addSource',
            grpc_dot_services_dot_source__pb2.SourceRequest.SerializeToString,
            grpc_dot_services_dot_source__pb2.SourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
