# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/news.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/news.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import author_pb2 as protos_dot_author__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/news.proto\x12\x04news\x1a\x13protos/author.proto\"\x8e\x01\n\x0eNewsAddRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08sourceId\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x10\n\x08\x61uthorId\x18\x05 \x01(\x05\x12\x0c\n\x04\x62ody\x18\x06 \x01(\t\x12\x10\n\x08postDate\x18\x07 \x01(\t\x12\x10\n\x08imageUrl\x18\x08 \x01(\t\"\xa3\x01\n\x0cNewsResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tsourceUrl\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12&\n\x06\x61uthor\x18\x05 \x01(\x0b\x32\x16.author.AuthorResponse\x12\x0c\n\x04\x62ody\x18\x06 \x01(\t\x12\x10\n\x08postDate\x18\x07 \x01(\t\x12\x10\n\x08imageUrl\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.news_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWSADDREQUEST']._serialized_start=49
  _globals['_NEWSADDREQUEST']._serialized_end=191
  _globals['_NEWSRESPONSE']._serialized_start=194
  _globals['_NEWSRESPONSE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
